platform:
  - x64
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 7 x64
  - npm install electron
  - npm install bower
  - npm install electron-builder
  - npm install
  - cd ccurl
  # - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  # - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  # - cl libccurl.cpp /LD /O2
  # - if not exist "win64" mkdir win64
  # - copy libccurl.dll win64\
  # - del libccurl.dll
  # - set Path2=%Path%
  - set Path=%Path%;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin\
  - gcc  libccurl.cpp -O3 -static  -lpthread -msse2 -shared -o libccurl.dll
  - if not exist "win64" mkdir win64
  - copy libccurl.dll win64\
  - del libccurl.dll
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - cl libccurl.cpp /LD /O2
  - if not exist "win32" mkdir win32
  - copy libccurl.dll win32\
  - del libccurl.dll
  - cd ..

build_script:
  - npm run compile:win
  - tree /f out

test: off

artifacts:

  # pushing a single file
   - path: out\*.exe

deploy:
  release: $(appveyor_repo_tag_name)
  description: ''
  provider: GitHub
  auth_token:
      secure: 3iQcaZ+ekUfV7qNqpOzlT1mY/pT4mhoNxxKsySYB643/Y6QWaPEEHqiOzHtQh+6k
  artifact: /.*\.exe/            
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        
 
