name: Linux Build
on: push
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          node --version
          yarn --version
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install build deps
        run: |
          sudo apt-get install \
          graphicsmagick \
          icnsutils \
          gcc-multilib \
          g++-multilib \
          libarchive-tools \
          rpm \
          xz-utils \
          libsecret-1-dev
      - name: Install deps
        run: yarn install
#      - name: Build libccurl
#        run: ./build-ccurl-linux.sh
      - env:
          # This one is available in Actions by default
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
        run: |
          yarn run compile:lin
          find out
      - uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: |
            out/*.AppImage
            out/*.tar.gz
            out/*-i386.AppImage
            out/*-ia32.tar.gz
            out/*.i686.rpm
            out/*.x86_64.rpm
            out/*_i386.deb
            out/*_amd64.deb
